version: "3.9"

services:
  simple:
    build:
      context: .
      dockerfile: docker/simple.Dockerfile
    container_name: sim_fut_simple
    environment:
      - CONTAINER_TYPE=simple
      - LEAGUE=${LEAGUE:-premier_league}
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./results:/app/results
    entrypoint: ["/app/docker/entrypoint.sh"]

  advanced:
    build:
      context: .
      dockerfile: docker/advanced.Dockerfile
    container_name: sim_fut_advanced
    environment:
      - CONTAINER_TYPE=advanced
      - LEAGUE=${LEAGUE:-premier_league}
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./results:/app/results
    entrypoint: ["/app/docker/entrypoint.sh"]

  interface:
    build:
      context: .
      dockerfile: docker/interface.Dockerfile
    container_name: sim_fut_interface
    environment:
      - CONTAINER_TYPE=interface
      - LEAGUE=${LEAGUE:-premier_league}
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./results:/app/results
    entrypoint: ["/app/docker/entrypoint.sh"]
